--------------------------------------------------------
--  File created - Tuesday-October-12-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTEXTS
--------------------------------------------------------

  CREATE TABLE "NHL"."CONTEXTS" 
   (	"TWEET_ID" NUMBER, 
	"DOMAIN_ID" NUMBER, 
	"DOMAIN_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"DOMAIN_DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"ENTITY_ID" NUMBER, 
	"ENTITY_NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"ENTITY_DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table HASHTAGS
--------------------------------------------------------

  CREATE TABLE "NHL"."HASHTAGS" 
   (	"TWEET_ID" NUMBER, 
	"START_POS" NUMBER, 
	"END_POS" NUMBER, 
	"TAG" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table MENTIONS
--------------------------------------------------------

  CREATE TABLE "NHL"."MENTIONS" 
   (	"TWEET_ID" NUMBER, 
	"START_POS" NUMBER, 
	"END_POS" NUMBER, 
	"USERNAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"USER_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table TWEETS
--------------------------------------------------------

  CREATE TABLE "NHL"."TWEETS" 
   (	"TWEET_ID" NUMBER, 
	"AUTHOR_ID" NUMBER, 
	"ATTACHMENTS" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"CONVERSATION_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"GEO" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"IN_REPLY_TO_USER_ID" NUMBER, 
	"LANG" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"POSSIBLY_SENSITIVE" NUMBER, 
	"RETWEET_COUNT" NUMBER, 
	"REPLY_COUNT" NUMBER, 
	"LIKE_COUNT" NUMBER, 
	"QUOTE_COUNT" NUMBER, 
	"TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"REPLIED_TO_ID" NUMBER, 
	"REPLY_SETTINGS" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"SOURCE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"TEXT" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"MATCHING_RULES" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "NHL"."USERS" 
   (	"USER_ID" NUMBER, 
	"TWEET_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE, 
	"DESCRIPTION" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"NAME" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"PROFILE_IMAGE_URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"PROTECTED" NUMBER, 
	"FOLLOWERS_COUNT" NUMBER, 
	"FOLLOWING_COUNT" NUMBER, 
	"TWEET_COUNT" NUMBER, 
	"LISTED_COUNT" NUMBER, 
	"URL" VARCHAR2(500 BYTE) COLLATE "USING_NLS_COMP", 
	"USERNAME" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"VERIFIED" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;


--------------------------------------------------------
--  Constraints for Table TWEETS
--------------------------------------------------------

  ALTER TABLE "NHL"."TWEETS" ADD PRIMARY KEY ("TWEET_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTEXTS
--------------------------------------------------------

  ALTER TABLE "NHL"."CONTEXTS" ADD CONSTRAINT "FK_TWEET_ID" FOREIGN KEY ("TWEET_ID")
	  REFERENCES "NHL"."TWEETS" ("TWEET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HASHTAGS
--------------------------------------------------------

  ALTER TABLE "NHL"."HASHTAGS" ADD CONSTRAINT "FK_HASHTAGS" FOREIGN KEY ("TWEET_ID")
	  REFERENCES "NHL"."TWEETS" ("TWEET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENTIONS
--------------------------------------------------------

  ALTER TABLE "NHL"."MENTIONS" ADD CONSTRAINT "FK_MENTIONS" FOREIGN KEY ("TWEET_ID")
	  REFERENCES "NHL"."TWEETS" ("TWEET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "NHL"."USERS" ADD CONSTRAINT "FK_USERS" FOREIGN KEY ("TWEET_ID")
	  REFERENCES "NHL"."TWEETS" ("TWEET_ID") ENABLE;
